server:
  port: 8081
spring:
  application:
    name: account-producer
  boot:
    admin:
      client:
        url: http://localhost:1111
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest 
  datasource:
      url: jdbc:mysql://localhost:3306/spring_security
      username: root
      password: shubhamsingh    
eureka:
   client:
    service-url:
     defaultZone: http://localhost:8761/eureka 
 
