server:
  port: 1115
spring:
  cloud:
    consul:
      discovery:
        register: true
        service-name: order-producer
      host: localhost
      port: 8500
  
  application:
    name: order-producer
    
    
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest