server:  port: 1212

spring:  datasource:    url: jdbc:mysql://localhost:3306/test    username: root    password: shubhamsingh    
  jpa:    hibernate:      ddl-auto: update    show-sql: true  data:    rest:      base-path: /api 