server:
  port: 8085
eureka:
  client:
    registerWithEureka: true
spring:
  application:
    name: Gateway-service
 
  cloud:
    config:
      uri: http://localhost:8888
  boot:
    admin:
      client:
        url:
        - http://localhost:1111
zuul:
  prefix: /api
  routes:
    account:
      path: /movie/**
      serviceId: movie-service
    customer:
      path: /user/**
      serviceId: user-service