server:
  port: 8082

spring:
  application:
    name: product-service-consumer
    
  boot:
    admin:
      client:
        url: http://localhost:9999
 
  cloud:
   consul:
      discovery:
        register: true
        service-name: product-service-consumer
      host: localhost
      port: 8500     
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coms
    username: root
    password: shubhamsingh
    
  jpa:
    show-sql: true
        hibernate:      ddl-auto: update
        
  data:
    rest:
      base-path: /api

