server:
  port: 1120
spring:
  cloud:
    consul:
      discovery:
        register: true
        service-name: product
      host: localhost
      port: 8500
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: product  jpa:    show-sql: true