server:
  port: 8082
spring:
  application:
    name: account-consumer
  boot:
    admin:
      client:
        url: http://localhost:1111
  h2:    console:      enabled: true
      path: /h2
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
eureka:
   client:
   
    service-url:
     defaultZone: http://localhost:8761/eureka/