server:
  port: 1115
spring:
  cloud:
    consul:
      discovery:
        register: true
        service-name: order
      host: localhost
      port: 8500
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: order-service
      jpa:    show-sql: true
    
